name: Run main.js

on:
  repository_dispatch: Trigger GH action

jobs:
  run-main-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: node main.js
