name: Run main.js

on:
  schedule:
    # - cron:  '1 3 * * *' # in UTC timezone
  workflow_dispatch:

jobs:
  run-main-js:
    runs-on: ubuntu-latest
    env:
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: node main.js
