name: Run main.js

on:
  repository_dispatch: [ trigger-gh-action ]

jobs:
  run-main-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: node main.js
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
